config/routes.rb
Rails.application.routes.draw do

  get "/", to: 'home#index', as: :home
  root to: 'home#index'

  get "/albums/new",          to: 'albums#new',    as: :new
  post "/albums",             to: "albums#create", as: :albums

  get "/albums/:id",            to: "albums#show",     as: :album
  get "/albums/edit/:id",       to: "albums#edit",     as: :album_edit
  patch "/albums/upvote/:id",   to: "albums#upvote",   as: :album_upvote

end

app/models/album.rb
class Album < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

    def new
      @album = Album.new
    end

    def create
      @album = Album.new(params.require(:album).permit(:title, :artist, :description))
      if @album.save
        redirect_to album_path
      else
        render :new
      end
    end

    def show
      @album = Album.find(params[:id])
    end

    def edit
      @album = Album.find(params[:id])
    end

    def upvote
      @album = Album.find(params[:id])
      @album.rating += 1
      @album.save
      redirect_to(album_path)

    end

    def update

    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/book_controller.rb
class BooksController < ApplicationController
end

app/controllers/concerns/index_controller.rb
class IndexController < ApplicationController
  def index
    @books  = Book.all.limit(10)
    @movies = Movie.all.limit(10)
    @albums = Album.all.limit(10)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books  = Book.all.limit(10)
    @movies = Movie.all.limit(10)
    @albums = Album.all.limit(10)
  end
end

app/controllers/movie_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_album_form.html.erb
<form role="form">
  <%= form_for @album do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
    </div><!--form-group-->

    <div class="form-group">
        <%= f.label :artist %>
        <%= f.text_field :artist, class: "form-control" %>
    </div><!--form-group-->

    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
    </div><!--form-group-->
    
        <%= f.submit "Save" %>

  <% end %>
</form>

app/views/albums/edit.html.erb
<h2>Edit <%= @album.title %></h2>
<%= render "album_form" %>

app/views/albums/new.html.erb
<h2>Add New Album</h2>
<%= render "album_form" %>

app/views/albums/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1><%= @album.title %> <small>Artist: <%= @album.artist %></small></h1>
    <h4>Rating: <%= @album.rating %></h4>
    <p>Description</p>

    <%= link_to "Upvote", album_upvote_path(@album), method:"patch" %>
  </div><!--col-lg-12-->
</div><!--row-->

app/views/home/index.html.erb
<div clas="row">

  <div class="col-md-4">
    <h3>Top Ten Albums</h3>
      <% @albums.each do |album| %>
          <h2><%= link_to album.title, album  %></a><small><%= album.rating  %></small></h2>
      <% end %>
    <%= link_to "View More Albums", home_path %>
  </div><!--albums col-md-4-->

  <div class="col-md-4">
    <h3>Top Ten Books</h3>
    <% @books  %>
    <%= link_to "View More Books", home_path %>
  </div><!--books col-md-4-->

  <div class="col-md-4">
    <h3>Top Ten Movies</h3>
    <% @movies  %>
    <%= link_to "View More Movies", home_path %>
  </div><!--movies col-md-4-->

</div><!--row-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rate It!</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= favicon_link_tag       'favicon.ico' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
  <div class="container">
    <div class="row">
      <div class="page-header">
          <h1><%= link_to "Rate It!", home_path %>
            <small>Rating the Best of Everything</small>
          </h1>
      </div><!--page header-->
    </div> <!--row-->
    </header>

    <%= yield %>

  </div><!--container-->
</body>
</html>